package com.assignment.assignment.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.assignment.assignment.custom.IntimePerMonthCount;
import com.assignment.assignment.models.IntimeAsset;
import com.assignment.assignment.repositories.IntimeAssetRepository;

@RestController
@RequestMapping("api/intimeasset")
public class IntimeAssetController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private IntimeAssetRepository repository;
	
	@GetMapping(path = "/all")
	public List<IntimeAsset> findAll() {
		// This returns a JSON or XML with the users
		return (List<IntimeAsset>) repository.findAll();
	}
	
	@PostMapping(path = "/add")
	public IntimeAsset AddIntimeAsset(@RequestBody IntimeAsset i) {
		IntimeAsset intimeAsset = new IntimeAsset(i.getId_asset(), i.getIntime_month());
		return repository.save(intimeAsset);
	}
	
	@GetMapping(path = "listAssetIntime")
	public List<IntimePerMonthCount> listAssetOverdue(){
		return repository.countIntimePerMonth();
	}
}
